name: sigillum
description: "Sigillum - Examen de Conciencia Estructurado"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  local_auth: ^3.0.1
  no_screenshot: ^1.1.0
  http: ^1.6.0
  flutter_markdown: ^0.7.7
  shared_preferences: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon_1024.png"
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: "assets/icon/icon_1024.png"

flutter:
  uses-material-design: true
  assets:
    - assets/rag/cic.json
    - assets/rag/catecismo.json
    - assets/icon/icon_1024.png
